sudo: required
language: python
services:
- docker
env:
  global: GKE_cluster_name=projects GKE_zone=us-central1-c GKE_project_id=personal-project-289714
before_install:
- openssl aes-256-cbc -K $encrypted_3dc22455e252_key -iv $encrypted_3dc22455e252_iv
  -in gcp-secret.json.enc -out gcp-secret.json -d
- mv gcp-secret.json ${HOME}/gcloud-service-key.json
- gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
- gcloud auth configure-docker --quiet
jobs:
  include:
  - stage: build-website
    script:
    - docker build . -t gcr.io/personal-project-289714/chess-website:$TRAVIS_BUILD_ID
    - gcloud docker -- push gcr.io/personal-project-289714/chess-website:$TRAVIS_BUILD_ID
  - stage: build-cron
    script:
    - docker build cron/email/ -t gcr.io/personal-project-289714/chess-arenas:$TRAVIS_BUILD_ID
    - gcloud docker -- push gcr.io/personal-project-289714/chess-arenas:$TRAVIS_BUILD_ID
  - stage: deploy-website
    script:
    - curl https://sdk.cloud.google.com | bash -s -- --disable-prompts > /dev/null
    - export PATH=${HOME}/google-cloud-sdk/bin:${PATH}
    - gcloud --quiet components install kubectl
    - gcloud container clusters get-credentials $GKE_cluster_name --zone $GKE_zone
      --project $GKE_project_id
    - kubectl set image deployment/chess-website chess-website=gcr.io/personal-project-289714/chess-website:$TRAVIS_BUILD_ID
      -n resume
