apiVersion: v1
kind: Service
metadata:
  name: chesssvc
  namespace: resume
  labels:
    app: chess-website
spec:
  selector:
    app: chess-website
    tier: deploy
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer
