apiVersion: apps/v1
kind: Deployment
metadata:
  name: chess_website
  namespace: resume
  labels:
    app: chess_website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chess_website
      tier: deploy
  template:
    metadata:
      labels:
        app: chess_website
        tier: deploy
    spec:
      containers:
        - name: chess_website
          image: gcr.io/personal-project-289714/chess_website:20201030010011
          ports:
          - containerPort: 8000
